default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: Nguyenvanloc...

development:
  database: BookApp_development
  <<: *default

test:
  database: BookApp_test
  <<: *default

production:
  database: BookApp_production
  <<: *default